import React, { useState, useEffect } from 'react';
import { Mail, Copy, MapPin, Briefcase, Clock, ExternalLink, RefreshCw } from 'lucide-react';
import jobsData from '../data/jobs';
import { calculateMatchScore } from '../utils/scoring';
import Button from '../components/Button';
import Card from '../components/Card';
import { Link } from 'react-router-dom';

const Digest = () => {
    const [digest, setDigest] = useState(null);
    const [preferences, setPreferences] = useState(null);
    const [loading, setLoading] = useState(false);

    // Get today's date string YYYY-MM-DD
    const getTodayDate = () => new Date().toISOString().split('T')[0];
    const digestKey = `jobTrackerDigest_${getTodayDate()}`;

    useEffect(() => {
        // Load Preferences
        const savedPrefs = localStorage.getItem('jobTrackerPreferences');
        if (savedPrefs) {
            setPreferences(JSON.parse(savedPrefs));
        }

        // Load Existing Digest
        const savedDigest = localStorage.getItem(digestKey);
        if (savedDigest) {
            setDigest(JSON.parse(savedDigest));
        }
    }, []);

    const generateDigest = () => {
        if (!preferences) return;

        setLoading(true);
        setTimeout(() => {
            // 1. Score all jobs
            const scoredJobs = jobsData.map(job => ({
                ...job,
                matchScore: calculateMatchScore(job, preferences)
            }));

            // 2. Filter by threshold (minMatchScore) or at least > 0
            const threshold = preferences.minMatchScore || 0;
            const validJobs = scoredJobs.filter(job => job.matchScore >= threshold && job.matchScore > 0);

            // 3. Sort: Match Score DESC, then Date Asc (freshness)
            validJobs.sort((a, b) => {
                if (b.matchScore !== a.matchScore) return b.matchScore - a.matchScore;
                return a.postedDaysAgo - b.postedDaysAgo;
            });

            // 4. Take Top 10
            const topJobs = validJobs.slice(0, 10);

            // 4. Save
            setDigest(topJobs);
            localStorage.setItem(digestKey, JSON.stringify(topJobs));
            setLoading(false);
        }, 800); // Simulate network/processing delay
    };

    const getDigestText = () => {
        if (!digest) return '';
        let text = `My 9AM Job Digest - ${getTodayDate()}\n\n`;
        text += `Top ${digest.length} Jobs For You\n\n`;

        digest.forEach((job, index) => {
            text += `${index + 1}. ${job.title} at ${job.company}\n`;
            text += `   Location: ${job.location} | Exp: ${job.experience}\n`;
            text += `   Match: ${job.matchScore}/100 | Link: ${job.applyUrl}\n\n`;
        });

        text += `Generated by Job Notification Tracker`;
        return text;
    };

    const handleCopy = () => {
        const text = getDigestText();
        navigator.clipboard.writeText(text);
        alert('Digest copied to clipboard!');
    };

    const handleEmail = () => {
        const text = getDigestText();
        const subject = encodeURIComponent(`My 9AM Job Digest - ${getTodayDate()}`);
        const body = encodeURIComponent(text);
        window.open(`mailto:?subject=${subject}&body=${body}`);
    };

    const handleRegenerate = () => {
        if (window.confirm("Are you sure? This will replace your existing daily digest.")) {
            generateDigest();
        }
    };

    if (!preferences) {
        return (
            <div style={{ padding: '40px', maxWidth: '800px', margin: '0 auto', textAlign: 'center', minHeight: '60vh', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}>
                <Mail size={48} color="var(--color-border)" style={{ marginBottom: '24px' }} />
                <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '2rem', marginBottom: '16px' }}>Daily Digest</h2>
                <p style={{ color: 'var(--color-subtext)', fontSize: '1.1rem', marginBottom: '24px' }}>
                    Set your preferences to activate personalized daily digests.
                </p>
                <Link to="/settings" style={{ textDecoration: 'none' }}>
                    <Button variant="primary">Set Preferences</Button>
                </Link>
            </div>
        );
    }

    return (
        <div style={{ padding: '24px', maxWidth: '800px', margin: '0 auto' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
                <h1 style={{ fontFamily: 'var(--font-serif)', fontSize: '2.5rem', margin: 0 }}>Daily Digest</h1>
                <span style={{ fontSize: '0.8rem', color: 'var(--color-subtext)', backgroundColor: '#eee', padding: '4px 8px', borderRadius: '4px' }}>
                    Demo Mode: 9AM trigger simulated
                </span>
            </div>

            {!digest ? (
                <div style={{ textAlign: 'center', padding: '60px 0', border: '2px dashed var(--color-border)', borderRadius: '8px' }}>
                    <h3 style={{ marginBottom: '16px', color: 'var(--color-text)' }}>Ready to generate today's digest?</h3>
                    <Button variant="primary" onClick={generateDigest} disabled={loading}>
                        {loading ? 'Generating...' : "Generate Today's 9AM Digest (Simulated)"}
                    </Button>
                </div>
            ) : (
                <>
                    <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px', marginBottom: '16px' }}>
                        <Button variant="secondary" onClick={handleRegenerate}>
                            <RefreshCw size={16} style={{ marginRight: '8px' }} /> Regenerate
                        </Button>
                        <Button variant="secondary" onClick={handleCopy}>
                            <Copy size={16} style={{ marginRight: '8px' }} /> Copy to Clipboard
                        </Button>
                        <Button variant="secondary" onClick={handleEmail}>
                            <Mail size={16} style={{ marginRight: '8px' }} /> Create Email Draft
                        </Button>
                    </div>

                    {digest.length === 0 ? (
                        <div style={{ textAlign: 'center', padding: '40px', color: 'var(--color-subtext)' }}>
                            <p>No matching roles found today based on your preferences. Check again tomorrow!</p>
                        </div>
                    ) : (
                        <Card style={{ padding: '0', overflow: 'hidden', border: '1px solid #e0e0e0' }}>
                            {/* Email Header */}
                            <div style={{ backgroundColor: '#f9f9f9', padding: '24px', borderBottom: '1px solid #eee', textAlign: 'center' }}>
                                <h2 style={{ fontFamily: 'var(--font-serif)', margin: '0 0 8px 0' }}>Top 10 Jobs For You</h2>
                                <p style={{ margin: 0, color: '#666', fontSize: '0.9rem' }}>9AM Digest • {new Date().toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
                            </div>

                            {/* Digest List */}
                            <div style={{ padding: '24px' }}>
                                {digest.map((job, index) => (
                                    <div key={job.id} style={{
                                        display: 'flex',
                                        justifyContent: 'space-between',
                                        alignItems: 'flex-start',
                                        paddingBottom: index !== digest.length - 1 ? '16px' : '0',
                                        marginBottom: index !== digest.length - 1 ? '16px' : '0',
                                        borderBottom: index !== digest.length - 1 ? '1px solid #eee' : 'none'
                                    }}>
                                        <div style={{ flex: 1 }}>
                                            <h4 style={{ margin: '0 0 4px 0', fontSize: '1.1rem', color: 'var(--color-text)' }}>
                                                {job.title} <span style={{ fontWeight: 400, color: '#666' }}>at {job.company}</span>
                                            </h4>
                                            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px', fontSize: '0.85rem', color: '#666' }}>
                                                <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                                    <MapPin size={14} /> {job.location}
                                                </span>
                                                <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                                    <Briefcase size={14} /> {job.experience}
                                                </span>
                                                <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                                    <Clock size={14} /> {job.postedDaysAgo === 0 ? 'Today' : `${job.postedDaysAgo}d ago`}
                                                </span>
                                            </div>
                                        </div>

                                        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '8px' }}>
                                            <div style={{
                                                backgroundColor: job.matchScore >= 80 ? 'var(--color-success)' : job.matchScore >= 60 ? 'var(--color-warning)' : '#999',
                                                color: 'white',
                                                padding: '2px 8px',
                                                borderRadius: '12px',
                                                fontSize: '0.75rem',
                                                fontWeight: 'bold'
                                            }}>
                                                {job.matchScore} Match
                                            </div>
                                            <a href={job.applyUrl} target="_blank" rel="noopener noreferrer" style={{ textDecoration: 'none' }}>
                                                <span style={{ color: 'var(--color-accent)', fontWeight: 600, fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: '4px' }}>
                                                    Apply <ExternalLink size={14} />
                                                </span>
                                            </a>
                                        </div>
                                    </div>
                                ))}
                            </div>

                            {/* Footer */}
                            <div style={{ backgroundColor: '#f9f9f9', padding: '16px', borderTop: '1px solid #eee', textAlign: 'center', color: '#888', fontSize: '0.8rem' }}>
                                This digest was generated based on your preferences. <Link to="/settings" style={{ color: 'var(--color-accent)' }}>Update settings</Link>
                            </div>
                        </Card>
                    )}
                </>
            )}
        </div>
    );
};

export default Digest;
